export const BUTTONS = [
  { value: "C", important: true, icon: "C", wide: false },
  { value: "+", important: true, icon: "+", wide: false },
  { value: "-", important: true, icon: "-", wide: false },
  { value: "*", important: true, icon: "*", wide: false },
  { value: "0", important: false, icon: "0", wide: false },
  { value: "1", important: false, icon: "1", wide: false },
  { value: "2", important: false, icon: "2", wide: false },
  { value: "3", important: false, icon: "3", wide: false },
  { value: "4", important: false, icon: "4", wide: false },
  { value: "5", important: false, icon: "5", wide: false },
  { value: "6", important: false, icon: "6", wide: false },
  { value: "7", important: false, icon: "7", wide: false },
  { value: "8", important: false, icon: "8", wide: false },
  { value: "9", important: false, icon: "9", wide: false },
  { value: "/", important: true, icon: "/", wide: false },
  { value: "%", important: true, icon: ".", wide: false },
  { value: "=", important: true, icon: "=", wide: true },
  { value: ".", important: true, icon: ".", wide: false },
];
